config/routes.rb
Rails.application.routes.draw do

 resources :teams
 resources :users

  get  'signup' => 'teams#new'
  get 'main'=> 'teams#show'

  root 'static_pages#home'
  get 'static_pages/about'
  get 'static_pages/start'


  get 'login_user' => 'sessions_for_users#new'
  post 'login_user'=> 'sessions_for_users#create'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup_users' => 'users#new'
end

app/models/team.rb
class Team < ActiveRecord::Base

  before_save {self.name = self.name.downcase}
  before_save {self.email = self.email.downcase}
  validates :name, presence: true, length: {maximum: 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:true, length: {maximum: 255},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}


  has_secure_password

  validates :password, presence:true, length:{minimum: 6},allow_nil: true
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, length: {maximum:50},presence: true
  validates :email, length: {maximum:255},presence:true,
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness:  {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum:6}, allow_nil: true

  belongs_to :team
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include SessionsForUsersHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 def new

 end

 def create

  team=Team.find_by(name: params[:session][:name].downcase)
  if team && team.authenticate(params[:session][:password])
    login_team  team


    params[:session][:remember_me] == '1' ? remember_team(team) : forget_team(team)

    redirect_to team
  else
    flash.now[:alert] = 'パスワードまたはチーム名が間違っています。'
    render 'new'
  end

end

 def destroy
  logout_team
  redirect_to root_path
 end
end

app/controllers/sessions_for_users_controller.rb
class SessionsForUsersController < ApplicationController
  def new
    if login_user?
     redirect_to current_user
    else
      @user_name = params[:name]
    end
  end

  def create

    user = User.find_by(name: params[:session][:name])

    if user && user.authenticate(params[:session][:password])
      login_user(user)
      redirect_to user
    else
      flash.now[:alert] = 'パスワードが違います'
      render 'new'
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def new
    @teams = Team.new
  end

  def show
    @teams = Team.find(params[:id])
  end

  def create
    @teams = Team.new(team_params)
    if @teams.save
      redirect_to @teams
    else
      render 'new'
    end
  end

  def team_params
    params.require(:team).permit(:name, :email, :password,:password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if login_user?
     redirect_to current_user
    else
      @user = User.new
      
    end
  end

  def create

    @user = User.new(user_params)

    if @user.save
      redirect_to current_team
    else
      render 'new'
    end

  end

  private

    def user_params
      params.require(:user).permit(:name,:email,:password,:password_digest,:team_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_for_users_helper.rb
module SessionsForUsersHelper
  def login_user(user)
    session[:user_id] = user.id
  end
  
  def current_team
    if session[:team_id]
      @current_team ||= Team.find_by(id: session[:team_id])
    elsif cookies.signed[:team_id]
      @current_team ||= Team.find_by(id: cookies.signed[:team_id])
    end
  end



  def login_user?
    !current_user.nil?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logout_user
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login_team(team)
    session[:team_id] = team.id
  end

  def current_team

    if session[:team_id]
      @current_team ||= Team.find_by(id: session[:team_id])
    elsif cookies.signed[:team_id]
      @current_team ||= Team.find_by(id: cookies.signed[:team_id])
    end

  end

  def login_team?
    !current_team.nil?
  end

  #クッキーにチームを保存する
  def remember_team(team)
    cookies.permanent.signed[:team_id] = team.id
  end

  def forget_team(team)
    cookies.delete(:team_id)
  end

  def logout_team
    forget_team(current_team)
    session.delete(:team_id)
    @current_team = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="page-footer">

<div class="footer-copyright">
  <div class="container">
    <adress>© Copyright Sh0</adress>
  </div>
</div>
</footer>

app/views/layouts/_header.html.erb
<header>

<nav>
  <div class="nav_wrapper">
      <span class="logo">
        <i class="fa fa-clock-o fa-1x icon"></i>
        <% if login_team? %>
          <%= link_to "ShareTime", current_team, class: "bland-logo" %>
        <% else %>
          <%= link_to "ShareTime", root_path, class: "bland-logo" %>
        <% end %>
        <i class="fa fa-share-alt icon"></i>
      </span>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li class="dropdown">
          <%= link_to "#", class: "dropdown-button" do%>
          <i class="material-icons">settings</i>
          <%end%>
        </li>

        <% if login_team? %>
          <li><%= link_to "ログアウト", logout_path, method: "delete" %></li>
          <li><%= link_to "チームページ", current_team %></li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>

      </ul>
  </div>
</nav>

</header>

app/views/layouts/_mini_disp.html.erb
<% if login_user? %>

<div class="mini-disp">

  <div class="row">
    <div class="col s4 offset-s10"><span class="card-panel name" style="border-radius:3px;"><%= current_user.name %></span></div>
  </div>

</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShareTime</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

    <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>

  <!-- font awsome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

<%= render 'layouts/header' %>
<%= render 'layouts/mini_disp' %>

<div class="container">
  <%= yield %>
</div>

<%= render 'layouts/footer' %>

<script>



function setTime(num) {
  var ret;

  if(num<10){ret = "0" + num;}
  else{ret = num};

  return ret;

}
function showClock1() {
   var nowTime = new Date();
   var nowHour = setTime(nowTime.getHours());
   var nowMin = setTime(nowTime.getMinutes());
   var nowSec = setTime(nowTime.getSeconds());
   var msg = nowHour + " : " + nowMin  ;
   document.getElementById("Clock").innerHTML = msg;
}

setInterval('showClock1()',1000);


$('.modal-trigger').leanModal();
$('select').material_select();

//時計の目標時間設定
$('.input-field .setting-time').click(function(){

  //時計アニメーションのインスタンス。
  var seconds = new ProgressBar.Circle('.timer', {
    duration: 150,
    color: "#FCB03C",
    trailColor: "#ddd",
    strokeWidth:2,
  });

  //時計計算用の変数
  var gettime = document.time_form.box.value ;
  var ttime = gettime-1;
  var temptime = gettime * 60;
  var second =0;
  var minute =0;

  //00:00の表示部分の関数
  function settime(time){
    if(time<10){
      ret = "0" + time
    }else if(time==0){
      ret = "00"
    }else{
      ret = time
    }
    return ret;
  }



  timer1 = setInterval(function(){
    var disp_minute = settime(ttime - minute);
    var disp_second = settime(59-second);


    seconds.animate( (minute*60+second)/ (gettime*60), function() {
        seconds.setText(disp_minute+":"+disp_second);
    });

    second++;
    if(second>59){
      second = 0;
      minute ++;
    }
  }, 1000);

  function stop_timer (){
    clearInterval(timer1);
  };

  $('.button ul li .stop-button').click(function(){
    stop_timer();
    $('.button ul li .stop-button').addClass('restart')
  });

  $('.button ul li .restart').click(function(){
    timer1;
  });

  $('.button ul li .start-button').addClass('disabled');
});
</script>
</body>
</html>

app/views/sessions_for_users/new.html.erb
<div class="card-panel login">

<div class="card-panel login_title">
    <h2>ー　ログイン　ー</h2>
</div>

<div class="row">

<% flash.each do |key,value| %>
  <div class = "card-panel <%= key %>"><%= value %></div>
<% end %>

  <%= form_for(:session,url: login_user_path)  do |f| %>


    <%= f.label "名前", class:'form' %>
    <p><%= @user_name %></p>
    <%= f.hidden_field :name,:value =>  @user_name %>

    <%= f.label "パスワード",class:'form' %>
    <%= f.password_field :password %>

    <%= f.submit "確認", class:"btn form-btn" %>


  <% end %>
</div>
</div>

app/views/shared/_error_message.html.erb
<% if @teams.errors.any? %>

<div class="error_message_box card-panel">

  <p>エラー：以下を確認してみてください</p>

  <div class="messages">
    <ul>
      <% @teams.errors.full_messages.each do |message| %>
        <div class="error card-panel "><li>・<%= message %></li></div>
      <% end %>
    </ul>
  </div>
</div>

<% end %>

app/views/shared/_error_message_for_user.html.erb
<% if @user.errors.any? %>

<div class="error_message_box card-panel">

  <p>エラー：以下を確認してみてください</p>

  <div class="messages">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <div class="error card-panel "><li>・<%= message %></li></div>
      <% end %>
    </ul>
  </div>
</div>

<% end %>

app/views/static_pages/about.html.erb
<div class="row">

<h2>about share time</h2>

  <p>プロジェクトが回らない？</p>

  <p>時間をうまく使えない？</p>

  <p>時間をチームで共有しよう</p>

  <p>Share time</p>

</div>

app/views/static_pages/home.html.erb
  <div class='row'>
  <div class="card-panel">

  <h2>時間の共有を始めましょう！</h2>

  <p>まずサインアップから。</p>
  <%= link_to "サインアップ", signup_path, class: "btn" %>
  </div>
  </div>

app/views/users/new.html.erb
<div class="card-panel signup">

<div class="card-panel signup_title">
    <h2>ー　メンバー登録　ー</h2>
</div>

<div class="row">


  <%= form_for(@user)  do |f| %>

  <%= render 'shared/error_message_for_user' %>

    <%= f.label "ニックネーム", class:'form' %>
    <%= f.text_field :name, placeholder:"ふなっしー" %>

    <%= f.label "メールアドレス", class:'form' %>
    <%= f.text_field :email, placeholder:"projects-name@example.com" %>

    <%= f.label "パスワード",class:'form' %>
    <%= f.password_field :password %>

    <%= f.label "パスワード（確認）",class:'form' %>
    <%= f.password_field :password_confirmation %>

    <%= f.hidden_field :team_id,:value => current_team.id %>

    <%= f.submit "メンバーになる！", class:"btn form-btn" %>

  <% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="user-main">
  <div class="card-panel main-panel">
  <div class="card-panel timer-background" style="width:400px; margin">
    <div class="timer"></div>
  </div>
    <div class="button">
      <ul>
        <li><a class="start-button btn waves-effect waves-light modal-trigger" href="#modal1">仕事をする！</a></li>
        <li><a class="stop-button btn">休憩！</a></li>
      </ul>
    </div>
  </div>
  <div id="modal1" class="modal">
    <div class="modal-content">
       <div class="input-field">
        <h4>目標時間</h4>
        <form name="time_form">
        <select name="box">
          <option value="15">15分</option>
          <option value="30">30分</option>
          <option value="60">60分</option>
          <option value="120">120分</option>
          <option value="180">180分</option>
          <option value="240">240分</option>
          <option value="300">300分</option>
          <option value="360">360分</option>
        </select>
        </form>
         <button class="btn setting-time modal-action modal-close">仕事を始める！</button>
      </div>
    </div>
  </div>
</div>